# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-MoinMoin
version:      0.53
version_from: lib/HTML/WikiConverter/MoinMoin.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.5
    Params::Validate:              0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
